#!/bin/bash

area=$(xrectsel $'%wx%h+%x+%y')
size=$(echo $area | cut -d'+' -f1)
x=$(echo $area | cut -d'+' -f2)
y=$(echo $area | cut -d'+' -f3)

alsa='-f alsa -i hw:0,0'
pulse='-f pulse -ac 2 -i default'

video="ffmpeg -hide_banner -f x11grab -show_region 1 -framerate 30 -video_size $size -i $DISPLAY+$x,$y"
sound_end="-c:v libx264 -preset ultrafast -c:a aac $2"
cmd=''

[ "$1" = "alsa" ] && cmd="$video $alsa $sound_end" || cmd="$video $pulse $sound_end"

$cmd
